In [30]:
#Question1

import numpy as np
import pandas as pd 

data=pd.read_csv("data.csv")
print(data)
data=np.array(data)
print(len(data))

     5.099999999999999645e+00  3.500000000000000000e+00  \
0                         4.9                       3.0   
1                         4.7                       3.2   
2                         4.6                       3.1   
3                         5.0                       3.6   
4                         5.4                       3.9   
..                        ...                       ...   
144                       6.7                       3.0   
145                       6.3                       2.5   
146                       6.5                       3.0   
147                       6.2                       3.4   
148                       5.9                       3.0   

     1.399999999999999911e+00  2.000000000000000111e-01  
0                         1.4                       0.2  
1                         1.3                       0.2  
2                         1.5                       0.2  
3                         1.4                       0.2  
4

In [33]:
#2 simon import numpy as np
#Load the data.csv file into a numpy array, let us call it X. How many samples are there in your new
#numpy array X?


x = np.genfromtxt("data.csv", delimiter = ',')
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [34]:
x.T



array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [35]:
#Question 2 Compute the average/mean of each column/feature for the entire dataset. That is, what is the mean
#of the 4 columns/features in the X numpy array/matrix which correspond to sepal length, sepal width,
#petal length and petal width.


avg_petal_length = x[:, 0].mean()  
avg_petal_width = x[:, 1].mean()
avg_sepal_length = x[:, 2].mean() 
avg_sepal_width = x[:, 3].mean() 

print('avg_petal_length is' ,avg_petal_length)
print('avg_petal_width is' ,avg_petal_width)
print('avg_sepal_length is' ,avg_sepal_length)
print('avg_sepal_width is' ,avg_sepal_width)


avg_petal_length is 5.843333333333334
avg_petal_width is 3.0540000000000003
avg_sepal_length is 3.758666666666666
avg_sepal_width is 1.1986666666666668


In [5]:
#question 3 Numpy is not well suited to loading/manipulating strings. We therefore have to find a different
#way to read the category string values from categories.csv than using a numpy function. Import the
#csv module and extract the category value strings and store it in a list.
#Hint The python function open and the csv function csv.reader are useful. The function
#csv.reader returns an object that is iterable, that is we can use the for loop to explore its contents
#one by one

import csv
list_cat =[]
    
with open ("categories.csv") as csv_file:
    cat = csv.reader(csv_file, delimiter =',')
    for row in cat:
        list_cat.append(row)



In [7]:
print(list_cat)

[['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-setosa'], ['Iris-versicolor'], ['Iris-versicolor'], ['Iris-versicolor'], ['Iris-versicolor'], ['Iris-versicolor'], ['Iris-versicolor'], ['Iris-versicolor'], ['

The above computed averages are useful to get a general understanding of the data but since we have
3 separate categories that these samples can belong to, it would be beneficial if we knew the average
of these columns/features per category. Please compute the average/mean of each column/feature
for the entire dataset per category. For example, you will, among other things, calculate the average
petal length for the category Iris-setosa.


In [26]:
data_connected = np.append(x, list_cat, axis = 1)
print(data_connected)

test = data_connected[:, 0:4].astype(np.float)
print (data_connected)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1